version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    working_dir: /app/frontend
    command: npm run dev
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
